export const mockTableData = [
  {
    _id: "6335654813c892dda954b493",
    title:
      "An Empirical Study of Test-Driven Development vs. Test-Last Development Using Eye Tracking",
    author:
      "Choma, J., Guerra, E. M., Silva, T. S. da, Albuquerque, T., Albuquerque, V. G. & Zaina, L. M.",
    journalName: "WBMA",
    year: 2019,
    volume: 1106,
    number: 1,
    pages: "11-24",
    doi: "https://doi.org/10.1007/978-3-030-36701-5_2",
    SEmethod: "TDD",
    claim: "Code Quality Improvement",
    evidence: "Weak support",
    status: "accepted",
    email: "",
  },
  {
    _id: "6335686930d930750b9cb2b3",
    title:
      "An experimental evaluation of test driven development vs. test-last development with industry professionals",
    author: "Munir, H., Wnuk, K., Petersen, K., Moayyed, M.",
    journalName: "",
    year: 2014,
    volume: null,
    number: null,
    pages: null,
    doi: "https://doi.org/10.1145/2601248.2601267",
    SEmethod: "TDD",
    claim: "",
    evidence: "",
    status: "moderator",
    email: "",
    __v: 0,
  },
  {
    _id: "63356a865c8a92bf42f5a974",
    title:
      "Realizing quality improvement through test driven development: results and experiences of four industrial teams",
    author: "Nagappan, N., Maximilien, E. M., Bhat, T., Williams, L.",
    journalName: "Empirical Software Engineering",
    year: 2008,
    volume: 13,
    number: 3,
    pages: "289–302",
    doi: "",
    SEmethod: "TDD",
    claim: "Product Quality Improvement",
    evidence: "Weak support",
    status: "accepted",
    email: "",
    __v: 0,
  },
  {
    _id: "6335b4ba495e4dadfed59877",
    title: "Test-Driven Development as a Defect-Reduction Practice. ",
    author: "Williams, L., Maximilien, E. M. & Vouk, M.",
    journalName:
      "4th International Symposium on Software Reliability Engineering",
    year: 2003,
    volume: null,
    number: null,
    pages: "34-45",
    doi: "https://doi.org/10.1109/issre.2003.1251029",
    SEmethod: "TDD",
    email: "",
    __v: 0,
    claim: "Product Quality Improvement",
    evidence: "Strong support",
    status: "accepted",
  },
  {
    _id: "6335b581a33bf06f00d943cf",
    title: "Book",
    author: "Hu",
    journalName: "play boy",
    year: 2021,
    volume: 21,
    number: 123,
    pages: "12",
    doi: "123",
    SEmethod: "Mob Programming",
    email: "tyt@autuni.ac.nz",
    __v: 0,
    status: "moderator",
  },
  {
    _id: "6336289d127e8ba2351ed691",
    title:
      "Does Test-Driven Development Really Improve Software Design Quality?",
    author: "Janzen, D. S.",
    journalName: "Software",
    year: null,
    volume: 25,
    number: 2,
    pages: "77-84",
    doi: "",
    SEmethod: "TDD",
    claim: "",
    evidence: "",
    status: "analyst",
    email: "",
    __v: 0,
  },
  {
    _id: "633628eb127e8ba2351ed693",
    title:
      "Comparative Case Study on the Impact of Test-Driven Development on Program Design and Test Coverage",
    author: "Siniaalto, M., Abrahamsson, P.",
    journalName: "cs.SE",
    year: 2017,
    volume: null,
    number: null,
    pages: "",
    doi: "1711.05082-284",
    SEmethod: "TDD",
    claim: "",
    evidence: "",
    status: "",
    email: "",
    __v: 0,
  },
];
